name: CI - Test and Build Docker Image

on:
    push:
        branches: [ main ]

jobs:
    test-with-dbs:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

            mongo:
                image: mongo:5
                env:
                    MONGO_INITDB_ROOT_USERNAME: root
                    MONGO_INITDB_ROOT_PASSWORD: root
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd="echo 'db.runCommand({ ping: 1 })' | mongo localhost/test --quiet"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

            redis:
                image: redis:6
                ports:
                    - 6379:6379


        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: Grant permission to gradlew
              run: chmod +x gradlew

            - name: Run tests with DB
              run: ./gradlew test -Dspring.profiles.active=ci
              env:
                  SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/test_db
                  SPRING_DATASOURCE_USERNAME: root
                  SPRING_DATASOURCE_PASSWORD: root
                  SPRING_DATA_MONGODB_URI: mongodb://root:root@localhost:27017/test?authSource=admin
                  SPRING_REDIS_HOST: localhost
                  SPRING_REDIS_PORT: 6379


    build-and-push:
        runs-on: ubuntu-latest
        needs: test-with-dbs

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: Grant permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle (no tests)
              run: ./gradlew clean build -x test -Dspring.profiles.active=ci

            - name: Set Docker Tag with Korea Time (KST)
              id: set_tag
              run: echo "tag_time=$(TZ=Asia/Seoul date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT

            - name: Log in to DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker Image with datetime tag
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-app:latest \
                               -t ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ steps.set_tag.outputs.tag_time }} .

            - name: Push Docker Images
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:latest
                  docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ steps.set_tag.outputs.tag_time }}
